### ISSUE TITLE
Milestone for Roadshow 1th

### ISSUE THREAD

**Issue by ragingwind** [pwa-workshop/namp-card#7]
- [x] : Codelab Guide Documentation

**Comment by ragingwind** [comment]
Web Manifest / Installable 은 추가 작업할 것이 없습니다. 생각나는건

- 카드 레이아웃/뷰티파이 작업, 그냥 간단하게 마무리 하면 될 것 같은데요

그 외로 뭐 더할 것이 있나요?

- for AMP?
- for SW?

**Comment by ragingwind** [comment]
friendly ping: @cwdoh @techhtml

**Comment by cwdoh** [comment]
아 서비스워커는 nampcard에서 first install, offline first, network first를 순서대로 구현해볼 생각이에요. 코드는 주말까지 커밋해둘께요.

**Comment by ragingwind** [comment]
스텝바이스텝 가이드가 있어야 할 것 같은데 제가 README.kr.md 에 러프하게 TOC 잡을테니 추가해주세요

**Comment by cwdoh** [comment]
넹

2016년 12월 8일 (목) 오후 12:07, Jimmy Moon <notifications@github.com>님이 작성:

**Comment by cwdoh** [comment]
알겠습니다. :)

**Comment by ragingwind** [comment]
문서 만들었습니다. 업데이트 부탁드려요 https://github.com/pwa-workshop/namp-card/blob/master/docs/codelab.kr.md

**Comment by cwdoh** [comment]
업데이트하고, 마크업 조금 손봤습니다.
